spring.datasource.url=jdbc:mysql://localhost:3306/fifaranglist?serverTimezone=Europe/Rome
spring.datasource.username=root
spring.datasource.password=root_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.web=OFF
logging.level.org.springframework.web.filter=OFF
logging.level.org.springframework.web.servlet.DispatcherServlet=OFF
logging.level.org.springframework.boot.web.servlet.filter=OFF